# Generated by Django 6.0.5 on 2026-05-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('floors_count', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['complex_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='crm.building')),
            ],
            options={
                'ordering': ['building_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], db_index=True, default='available', max_length=16)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('mortgage', 'Mortgage'), ('installment', 'Installment')], db_index=True, default='cash', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='crm.building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='crm.floor')),
            ],
            options={
                'ordering': ['building_id', 'floor__number', 'number', 'id'],
            },
        ),
        migrations.AddField(
            model_name='building',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='crm.residentialcomplex'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='lead', max_length=16)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.apartment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['apartment', 'status'], name='crm_deal_apartme_8bb2fc_idx'), models.Index(fields=['client', 'status'], name='crm_deal_client__7c28bd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['lead', 'in_progress'])), fields=('apartment',), name='unique_active_deal_per_apartment')],
            },
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_floor_number_per_building'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['building', 'status'], name='crm_apartme_buildin_b4b48b_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['floor', 'status'], name='crm_apartme_floor_i_ae1b6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='unique_apartment_number_per_building'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('complex', 'name'), name='unique_building_name_per_complex'),
        ),
    ]
