# Generated by Django 6.0.5 on 2026-05-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_aichatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='reserved_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('in_progress', 'In progress'), ('closed', 'Closed'), ('canceled', 'Canceled'), ('lost', 'Lost')], db_index=True, default='lead', max_length=16),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('comment', 'Comment'), ('call', 'Call')], db_index=True, default='comment', max_length=16)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['client', 'note_type'], name='crm_clientn_client__6f0881_idx')],
            },
        ),
    ]
